package com.shimmer.store.models.myOrdersDetail

data class ItemOrderDetail(
    val base_currency_code: String,
    val base_discount_amount: Int,
    val base_discount_tax_compensation_amount: Int,
    val base_grand_total: Double = 0.0,
    val base_shipping_amount: Int,
    val base_shipping_discount_amount: Int,
    val base_shipping_discount_tax_compensation_amnt: Int,
    val base_shipping_incl_tax: Double = 0.0,
    val base_shipping_tax_amount: Int,
    val base_subtotal: Double = 0.0,
    val base_subtotal_incl_tax: Int,
    val base_tax_amount: Int,
    val base_to_global_rate: Int,
    val base_to_order_rate: Int,
    val base_total_due: Int,
    val billing_address: BillingAddress,
    val billing_address_id: Int,
    val created_at: String,
    val customer_email: String,
    val customer_firstname: String,
    val customer_gender: Int,
    val customer_group_id: Int,
    val customer_id: Int,
    val customer_is_guest: Int,
    val customer_lastname: String,
    val customer_note_notify: Int,
    val discount_amount: Int,
    val discount_tax_compensation_amount: Int,
    val entity_id: Int,
    val extension_attributes: ExtensionAttributes,
    val global_currency_code: String,
    val grand_total: Int,
    val increment_id: String,
    val is_virtual: Int,
    val items: List<ItemX> = ArrayList(),
    val order_currency_code: String,
    val payment: Payment,
    val protect_code: String,
    val quote_id: Int,
    val remote_ip: String,
    val shipping_amount: Int,
    val shipping_description: String,
    val shipping_discount_amount: Int,
    val shipping_discount_tax_compensation_amount: Int,
    val shipping_incl_tax: Int,
    val shipping_tax_amount: Int,
    val state: String,
    val status: String,
    val status_histories: List<Any>,
    val store_currency_code: String,
    val store_id: Int,
    val store_name: String,
    val store_to_base_rate: Int,
    val store_to_order_rate: Int,
    val subtotal: Int,
    val subtotal_incl_tax: Int,
    val tax_amount: Int,
    val total_due: Int,
    val total_item_count: Int,
    val total_qty_ordered: Int,
    val updated_at: String,
    val weight: Int,
    val msg: Int
)