package com.klifora.franchise.models.myOrdersDetail

data class ItemX(
    val amount_refunded: Double = 0.0,
    val base_amount_refunded: Double = 0.0,
    val base_discount_amount: Double = 0.0,
    val base_discount_invoiced: Double = 0.0,
    val base_discount_tax_compensation_amount: Double = 0.0,
    val base_original_price: Double = 0.0,
    val base_price: Double = 0.0,
    val base_price_incl_tax: Double = 0.0,
    val base_row_invoiced: Int,
    val base_row_total: Double = 0.0,
    val base_row_total_incl_tax: Double = 0.0,
    val base_tax_amount: Double = 0.0,
    val base_tax_invoiced: Double,
    val created_at: String,
    val discount_amount: Double = 0.0,
    val discount_invoiced: Double = 0.0,
    val discount_percent: Double = 0.0,
    val discount_tax_compensation_amount: Double = 0.0,
    val free_shipping: Double = 0.0,
    val is_qty_decimal: Int,
    val is_virtual: Int,
    val item_id: Int,
    val name: String,
    val no_discount: Double = 0.0,
    val order_id: Int,
    val original_price: Double = 0.0,
    val price: Double = 0.0,
    val price_incl_tax: Double = 0.0,
    val product_id: Int,
    val product_type: String,
    val qty_canceled: Int,
    val qty_invoiced: Int,
    val qty_ordered: Int,
    val qty_refunded: Int,
    val qty_shipped: Int,
    val quote_item_id: Int,
    val row_invoiced: Int,
    val row_total: Double = 0.0,
    val row_total_incl_tax: Double = 0.0,
    val row_weight: Double = 0.0,
    val sku: String,
    val store_id: Int,
    val tax_amount: Double = 0.0,
    val tax_invoiced: Double = 0.0,
    val tax_percent: Double = 0.0,
    val updated_at: String,
    val weight: Double = 0.0,
    var isComplete: Boolean = false,
    )