package com.shimmer.store.networking


const val BASE_URL = "https://shop.vegasega.com/rest/"
const val URL = BASE_URL+"V1/"


const val ADMIN_TOKEN = "integration/admin/token"
const val CUSTOMER_LOGIN_TOKEN = "integration/customer/token"
const val CUSTOMER_DETAIL = "customers/me"




const val mobile_no = "mobile_no"
const val slug = "slug"
const val forgot = "forgot"
const val user_type = "user_type"
const val otp = "otp"
const val mobile_number = "mobile_number"
const val password = "password"
const val login = "login"
const val mobile_token = "mobile_token"
const val user_id = "user_id"
const val vendor_first_name = "vendor_first_name"
const val vendor_last_name = "vendor_last_name"
const val signup = "signup"
const val user_role = "user_role"
const val parent_first_name = "parent_first_name"
const val parent_last_name = "parent_last_name"
const val gender = "gender"
const val date_of_birth = "date_of_birth"
const val social_category = "social_category"
const val education_qualification = "education_qualification"
const val marital_status = "marital_status"
const val spouse_name = "spouse_name"
const val residential_state = "residential_state"
const val residential_district = "residential_district"
const val residential_municipality_panchayat = "residential_municipality_panchayat"
const val residential_pincode = "residential_pincode"
const val residential_address = "residential_address"
const val type_of_marketplace = "type_of_marketplace"
const val marketpalce_others = "marketpalce_others"
const val type_of_vending = "type_of_vending"
const val vending_others = "vending_others"
const val total_years_of_business = "total_years_of_business"
const val vending_time_from = "vending_time_from"
const val vending_time_to = "vending_time_to"
const val vending_state = "vending_state"
const val vending_district = "vending_district"
const val vending_municipality_panchayat = "vending_municipality_panchayat"
const val vending_pincode = "vending_pincode"
const val vending_address = "vending_address"
const val local_organisation = "local_organisation"
const val vending_documents = "vending_documents"
const val availed_scheme = "availed_scheme"
const val profile_image_name = "profile_image_name"
const val identity_image_name = "identity_image_name"
const val shop_image = "shop_image"
const val cov_image = "cov_image"
const val lor_image = "lor_image"
const val survey_receipt_image = "survey_receipt_image"
const val challan_image = "challan_image"
const val approval_letter_image = "approval_letter_image"
const val state_id = "state_id"
const val district_id = "district_id"
const val delete_account = "delete_account"
const val type = "type"
const val subject = "subject"
const val complaint_type = "complaint_type"
const val name = "name"
const val message = "message"
const val media = "media"
const val status = "status"
const val municipality_id = "municipality_id"
const val page = "page"
const val search_input = "search_input"
const val feedback_id = "feedback_id"
const val reply = "reply"
const val is_read = "is_read"
const val member_id = "member_id"
const val nomineeSquare = "nominee[]"
const val scheme_id = "scheme_id"
const val notification = "notification"
const val language = "language"
const val transaction_id = "transaction_id"
const val no_of_month_year = "no_of_month_year"
const val month_year = "month_year"
const val membership_id = "membership_id"
const val order_id = "order_id"
const val date_time = "date_time"
const val plan_type = "plan_type"
const val payment_method = "payment_method"
const val payment_status = "payment_status"
const val payment_validity = "payment_validity"
const val net_amount = "net_amount"
const val coupon_discount = "coupon_discount"
const val coupon_amount = "coupon_amount"
const val gst_rate = "gst_rate"
const val gst_amount = "gst_amount"
const val total_amount = "total_amount"



const val USER_TYPE = "member"
const val PING = "8.8.8.8"


//const val TRANSLATE_URL = "https://translation.googleapis.com/language/"
//const val TRANSLATE = "translate/v2?key="

const val TRANSLATE_URL = "https://translate.googleapis.com/translate_a/"
const val TRANSLATE = "single?client=gtx&sl=en&dt=t"


const val Screen = "screen"
const val Start = "Start"
const val Main = "Main"
const val CompleteRegister = "CompleteRegister"
const val LoginPassword = "LoginPassword"
const val LoginOtp = "LoginOtp"

const val IS_LANGUAGE = true
const val IS_LANGUAGE_ALL = false

const val RETRY_COUNT = 1

